INKSCAPE?=inkscape
OPTIPNG?=optipng -o7 --strip all --quiet
SCSS?=sassc

DEFAULT_THEME_COLOR?=\#2777ff
COLOR_VARIANTS?=Black Blue Brown Cyan Green Grey Magenta Orange Red Teal Violet White Yellow

COLOR_Black?=\#000000
TEXT_COLOR_Black?=\#f4f4f7

COLOR_Blue?=\#2777ff
TEXT_COLOR_Blue?=\#f4f4f7

COLOR_Brown?=\#c37837
TEXT_COLOR_Brown?=\#f4f4f7

COLOR_Cyan?=\#0ccfd9
TEXT_COLOR_Cyan?=\#f4f4f7

COLOR_Green?=\#06a284
TEXT_COLOR_Green?=\#f4f4f7

COLOR_Grey?=\#737680
TEXT_COLOR_Grey?=\#f4f4f7

COLOR_Magenta?=\#cd0245
TEXT_COLOR_Magenta?=\#f4f4f7

COLOR_Orange?=\#fd7d00
TEXT_COLOR_Orange?=\#f4f4f7

COLOR_Red?=\#ec0101
TEXT_COLOR_Red?=\#f4f4f7

COLOR_Teal?=\#0099a1
TEXT_COLOR_Teal?=\#f4f4f7

COLOR_Violet?=\#962ac3
TEXT_COLOR_Violet?=\#f4f4f7

COLOR_White?=\#f4f4f7
TEXT_COLOR_White?=\#000000

COLOR_Yellow?=\#ffd86e
TEXT_COLOR_Yellow?=\#000000

