INKSCAPE?=inkscape
OPTIPNG?=optipng -o7 --strip all --quiet
SCSS?=sassc

DEFAULT_THEME_COLOR?=\#8b9cbe
COLOR_VARIANTS ?=  Black Grey White 

UNWANTED_VARIANTS ?= 

COLOR_Black?=\#1b1d24
TEXT_COLOR_Black?=\#f4f4f7


COLOR_Grey?=\#555e70
TEXT_COLOR_Grey?=\#f4f4f7

COLOR_White?=\#f4f4f7
TEXT_COLOR_White?=\#1b1d24